import {AiFillStar} from "react-icons/ai";

const data =[
    {
        img:"https://m.media-amazon.com/images/I/716Inzq-uoL._AC_UL320_.jpg",
        title:"Zapato adidas",
        star:<AiFillStar className="rating-star"/>,
        reviews:"(123 reviews)",
        prevPrice:"$50,00",
        newPrice:"80",
        company:"Adidas",
        color:"white",
        category:"zapatos",
    },
    {
        img:"https://m.media-amazon.com/images/I/71WEVjm3aWL._AC_UL320_.jpg",
        title:"Botin adidas",
        star:<AiFillStar className="rating-star"/>,
        reviews:"(321 reviews)",
        prevPrice:"$90,00",
        newPrice:"100",
        company:"Adidas",
        color:"black",
        category:"botines",
    },
    {
        img:"https://m.media-amazon.com/images/I/61z3VoDZJkL._AC_UL320_.jpg",
        title:"Zapatilla Nike ",
        star:<AiFillStar className="rating-star"/>,
        reviews:"(100 reviews)",
        prevPrice:"$110,00",
        newPrice:"300",
        company:"Nike",
        color:"blue",
        category:"zapatillas",
    },
    {
        img:"https://m.media-amazon.com/images/I/71Y3nGKPwcL._AC_UL320_.jpg",
        title:"Zapatilla Nike Jordan",
        star:<AiFillStar className="rating-star"/>,
        reviews:"(200 reviews)",
        prevPrice:"$200,00",
        newPrice:"150",
        company:"Nike",
        color:"red",
        category:"zapatillas",
    },
    {
        img:"https://m.media-amazon.com/images/I/61bloZ0gueL._AC_UL320_.jpg",
        title:"Buzo puma",
        star:<AiFillStar className="rating-star"/>,
        reviews:"(1500 reviews)",
        prevPrice:"$140,00",
        newPrice:"110",
        company:"Puma",
        color:"red",
        category:"camperas",
    },
    {
        img:"https://m.media-amazon.com/images/I/81PKxiu77TS._AC_UL320_.jpg",
        title:"Campera puma",
        star:<AiFillStar className="rating-star"/>,
        reviews:"(2000 reviews)",
        prevPrice:"$100,00",
        newPrice:"120",
        company:"Puma",
        color:"blue",
        category:"camperas",
    },
];

export default data;